{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 8278,
          "sha512": "bf688af2510b9fc31dd30cab7da3eb96fffca464f04f93230a2906ce8c5e09a89c44111986700a96bcd3402fe9e649754c8f798a43bfaf2fd0334cc62c3a2def",
          "sha256": "606ee8bff432a1d9310216380ba592f3d05832716f02284aa15aa5de0d64f3ee",
          "sha1": "44b423c6c28c384aecb7c43400e989633349a402",
          "md5": "b950507c6f4d3f10649e38defa212273"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.aar",
          "url": "package_info_plus_debug-1.0.aar",
          "size": 8278,
          "sha512": "bf688af2510b9fc31dd30cab7da3eb96fffca464f04f93230a2906ce8c5e09a89c44111986700a96bcd3402fe9e649754c8f798a43bfaf2fd0334cc62c3a2def",
          "sha256": "606ee8bff432a1d9310216380ba592f3d05832716f02284aa15aa5de0d64f3ee",
          "sha1": "44b423c6c28c384aecb7c43400e989633349a402",
          "md5": "b950507c6f4d3f10649e38defa212273"
        }
      ]
    }
  ]
}
