{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.wakelock",
    "module": "wakelock_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 18603,
          "sha512": "ca2cfd07f2e294e1a25f000fa4c12b5d25fc3c2468d773d4a493784e804cceb6ac4853048746ce0a3291955194f167191f4a96b297d5cf57df899cc74ada536f",
          "sha256": "7556f05a54d8d20377d29ac70028aad9f1dac005a6d7467b960c8f19eb99f377",
          "sha1": "fce3b40fb91b3edd44133bdb0a4ad31b47dd64a8",
          "md5": "e1686c2a26cf61f4cf2bddea95eabe1b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 18603,
          "sha512": "ca2cfd07f2e294e1a25f000fa4c12b5d25fc3c2468d773d4a493784e804cceb6ac4853048746ce0a3291955194f167191f4a96b297d5cf57df899cc74ada536f",
          "sha256": "7556f05a54d8d20377d29ac70028aad9f1dac005a6d7467b960c8f19eb99f377",
          "sha1": "fce3b40fb91b3edd44133bdb0a4ad31b47dd64a8",
          "md5": "e1686c2a26cf61f4cf2bddea95eabe1b"
        }
      ]
    }
  ]
}
