{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.imagegallerysaver",
    "module": "image_gallery_saver_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_debug-1.0.aar",
          "url": "image_gallery_saver_debug-1.0.aar",
          "size": 10839,
          "sha512": "bea6b18f1b1dcc1054a0915945c7d2094d65b2fb67036bf613049b51fc319962d1cebdc93b3d710381f480b330b33d896bf1bcfc14aadaba74c7a6b79b3d3588",
          "sha256": "89337475249cbf020ada1f12e417cf3a992c8b92abf3c90cd3da7de4eb887df1",
          "sha1": "50d79d583af11c64e39ffce8aa0b582794d7bfcc",
          "md5": "46ea9ecf0b8e9905553cea3e732947a0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_debug-1.0.aar",
          "url": "image_gallery_saver_debug-1.0.aar",
          "size": 10839,
          "sha512": "bea6b18f1b1dcc1054a0915945c7d2094d65b2fb67036bf613049b51fc319962d1cebdc93b3d710381f480b330b33d896bf1bcfc14aadaba74c7a6b79b3d3588",
          "sha256": "89337475249cbf020ada1f12e417cf3a992c8b92abf3c90cd3da7de4eb887df1",
          "sha1": "50d79d583af11c64e39ffce8aa0b582794d7bfcc",
          "md5": "46ea9ecf0b8e9905553cea3e732947a0"
        }
      ]
    }
  ]
}
