{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26712,
          "sha512": "72975b930c79115ad8ff3f48b7b5a5fc85dcc5a9f26b287fc3665faa2e6e9e30f70c76d07c6a4159d994469cc8e11eb12faf8a696da383e83e6e3189a6a134c2",
          "sha256": "6d9ccd7da4654b0fe0703cc997c95da21e665a510b8c00b4045d0b9c96206a8f",
          "sha1": "86ee9fb47ed7df1db9635b324f6f086d4bd07568",
          "md5": "094704b7f0292fc0104264acecc1c312"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 26712,
          "sha512": "72975b930c79115ad8ff3f48b7b5a5fc85dcc5a9f26b287fc3665faa2e6e9e30f70c76d07c6a4159d994469cc8e11eb12faf8a696da383e83e6e3189a6a134c2",
          "sha256": "6d9ccd7da4654b0fe0703cc997c95da21e665a510b8c00b4045d0b9c96206a8f",
          "sha1": "86ee9fb47ed7df1db9635b324f6f086d4bd07568",
          "md5": "094704b7f0292fc0104264acecc1c312"
        }
      ]
    }
  ]
}
