{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30045,
          "sha512": "22dff4934b57631c004ad7ea35a190010c709ef7bb79eaea7e20586b31c82a8d013dbe3225346362aa1efb27df012ae42ee2f58fe56e315dd23a677aedb6a5b0",
          "sha256": "bc29cbce618036c399e3a9b1be7bd586c593a30f5f5149d9db4278fbdb5e8e55",
          "sha1": "3d799df36dc6ec2647be0866bfdcb11ef3c001c6",
          "md5": "48d409f4f06aedab425fe52ab2b507b3"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_debug-1.0.aar",
          "url": "permission_handler_android_debug-1.0.aar",
          "size": 30045,
          "sha512": "22dff4934b57631c004ad7ea35a190010c709ef7bb79eaea7e20586b31c82a8d013dbe3225346362aa1efb27df012ae42ee2f58fe56e315dd23a677aedb6a5b0",
          "sha256": "bc29cbce618036c399e3a9b1be7bd586c593a30f5f5149d9db4278fbdb5e8e55",
          "sha1": "3d799df36dc6ec2647be0866bfdcb11ef3c001c6",
          "md5": "48d409f4f06aedab425fe52ab2b507b3"
        }
      ]
    }
  ]
}
