{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.hunghd.flutter.plugins.imagecropper",
    "module": "image_cropper_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 25629,
          "sha512": "b300f577245d80fb09d6a6b3d61320daae79f07faf9ec473015af7cce24244d2b521ef216eaeb1bafd4836d8529a8291d0144623de09f705b833430822c24e5f",
          "sha256": "ab16ed99d6b0db348c7d66c21040fd54697e202e68eddd1effaffb5854241681",
          "sha1": "78201537458e98ef611da89cfd439234149623ee",
          "md5": "df34aeda7b2e8bc1ee40b37136c7ae72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 25629,
          "sha512": "b300f577245d80fb09d6a6b3d61320daae79f07faf9ec473015af7cce24244d2b521ef216eaeb1bafd4836d8529a8291d0144623de09f705b833430822c24e5f",
          "sha256": "ab16ed99d6b0db348c7d66c21040fd54697e202e68eddd1effaffb5854241681",
          "sha1": "78201537458e98ef611da89cfd439234149623ee",
          "md5": "df34aeda7b2e8bc1ee40b37136c7ae72"
        }
      ]
    }
  ]
}
