{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.canardoux.fluttersound",
    "module": "flutter_sound_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_release-1.0.aar",
          "url": "flutter_sound_release-1.0.aar",
          "size": 30080,
          "sha512": "9bb61c0e6957efe3c5ec883688107fa8bd5749b2b064f548b778017bd87b0845c61e29690ec9371e86468c827d9318685eadbe4f96655a3462d2872b58f20e31",
          "sha256": "852f64fa6f3bd6cf3dbe6d3167fb9eb4b5ecbebf7e6c9e0447ae2d1df0e3320f",
          "sha1": "b069e00ef4a86ef87f605b0d1317af9b12abb459",
          "md5": "28ab1a1a5466317f9d540b5de3b08cac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.canardoux",
          "module": "flutter_sound_core",
          "version": {
            "requires": "9.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_release-1.0.aar",
          "url": "flutter_sound_release-1.0.aar",
          "size": 30080,
          "sha512": "9bb61c0e6957efe3c5ec883688107fa8bd5749b2b064f548b778017bd87b0845c61e29690ec9371e86468c827d9318685eadbe4f96655a3462d2872b58f20e31",
          "sha256": "852f64fa6f3bd6cf3dbe6d3167fb9eb4b5ecbebf7e6c9e0447ae2d1df0e3320f",
          "sha1": "b069e00ef4a86ef87f605b0d1317af9b12abb459",
          "md5": "28ab1a1a5466317f9d540b5de3b08cac"
        }
      ]
    }
  ]
}
