{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.canardoux.fluttersound",
    "module": "flutter_sound_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_debug-1.0.aar",
          "url": "flutter_sound_debug-1.0.aar",
          "size": 30973,
          "sha512": "ce9c8dd0dbc36e8207b889f82eb9269a6e69240da742333e90f979d64866a05ebaa8b4882c2a9a9395d5fb71fd0ccccf4e4144dc0861bc777457384af7534409",
          "sha256": "04561b762655e52c9b9acdd0208464da97a667473c299f216b873b53b4636d95",
          "sha1": "4c33455db9f12316780ca980a233df8676e3bf31",
          "md5": "14510ddeb3a37ed0462ff4fffc3b1669"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.canardoux",
          "module": "flutter_sound_core",
          "version": {
            "requires": "9.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_debug-1.0.aar",
          "url": "flutter_sound_debug-1.0.aar",
          "size": 30973,
          "sha512": "ce9c8dd0dbc36e8207b889f82eb9269a6e69240da742333e90f979d64866a05ebaa8b4882c2a9a9395d5fb71fd0ccccf4e4144dc0861bc777457384af7534409",
          "sha256": "04561b762655e52c9b9acdd0208464da97a667473c299f216b873b53b4636d95",
          "sha1": "4c33455db9f12316780ca980a233df8676e3bf31",
          "md5": "14510ddeb3a37ed0462ff4fffc3b1669"
        }
      ]
    }
  ]
}
