{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7979,
          "sha512": "c0d15d28a31fd002da78cb3ea1aa28657f16ede9c836cb76a1fbc9088a1ec3df703b300fbf64b7baf599dadfcef1ae8f07b3c7fe9b8185d7a346cccaa649766d",
          "sha256": "a423d8d10777173744a31df09c1a78e78f39a29282ac6736e0bea16cc6fdfdd5",
          "sha1": "2f2e86a91a74196c9352bd0d26c5d4cb5739ae47",
          "md5": "437d09deba87fffc2d455cf520c757b2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 7979,
          "sha512": "c0d15d28a31fd002da78cb3ea1aa28657f16ede9c836cb76a1fbc9088a1ec3df703b300fbf64b7baf599dadfcef1ae8f07b3c7fe9b8185d7a346cccaa649766d",
          "sha256": "a423d8d10777173744a31df09c1a78e78f39a29282ac6736e0bea16cc6fdfdd5",
          "sha1": "2f2e86a91a74196c9352bd0d26c5d4cb5739ae47",
          "md5": "437d09deba87fffc2d455cf520c757b2"
        }
      ]
    }
  ]
}
