{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.imagegallerysaver",
    "module": "image_gallery_saver_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_profile-1.0.aar",
          "url": "image_gallery_saver_profile-1.0.aar",
          "size": 10358,
          "sha512": "0dd414c2ac6be22c87cbe2a6a031c81acc057c39ea94aa74198aa0f6d38a5a14192f3c47cfec84407b830eb2367b33e12d1fcef7ed166b7a9d644503475373ae",
          "sha256": "0469f6c6e834594d25bcc1faaed47049c1b908fe9cbd9e144f19774b85373822",
          "sha1": "f5ad8b77e09aae73687b778cf98a155d77305983",
          "md5": "b852d1aaab9f3efebc1a5ea30ac0477c"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_profile-1.0.aar",
          "url": "image_gallery_saver_profile-1.0.aar",
          "size": 10358,
          "sha512": "0dd414c2ac6be22c87cbe2a6a031c81acc057c39ea94aa74198aa0f6d38a5a14192f3c47cfec84407b830eb2367b33e12d1fcef7ed166b7a9d644503475373ae",
          "sha256": "0469f6c6e834594d25bcc1faaed47049c1b908fe9cbd9e144f19774b85373822",
          "sha1": "f5ad8b77e09aae73687b778cf98a155d77305983",
          "md5": "b852d1aaab9f3efebc1a5ea30ac0477c"
        }
      ]
    }
  ]
}
