{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.imagegallerysaver",
    "module": "image_gallery_saver_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_release-1.0.aar",
          "url": "image_gallery_saver_release-1.0.aar",
          "size": 10359,
          "sha512": "6346f3406caa7e5542ad23e7210b1be2a4e0f2bb1acae4d071410946e2c6db867f225b49bbb05618bdb4538653339bc70e848a6bb6d5afdc0a10145a50e0b538",
          "sha256": "abf705b678cc54ef0a1f4724a58a2d54a1fe70f8fc5fe0c3be0f635244862655",
          "sha1": "7d2b546e58ebea6e662d8f9a93e839cf127b446a",
          "md5": "0a93db001716b7855ac4070cc060c63a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "image_gallery_saver_release-1.0.aar",
          "url": "image_gallery_saver_release-1.0.aar",
          "size": 10359,
          "sha512": "6346f3406caa7e5542ad23e7210b1be2a4e0f2bb1acae4d071410946e2c6db867f225b49bbb05618bdb4538653339bc70e848a6bb6d5afdc0a10145a50e0b538",
          "sha256": "abf705b678cc54ef0a1f4724a58a2d54a1fe70f8fc5fe0c3be0f635244862655",
          "sha1": "7d2b546e58ebea6e662d8f9a93e839cf127b446a",
          "md5": "0a93db001716b7855ac4070cc060c63a"
        }
      ]
    }
  ]
}
