{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28749,
          "sha512": "7514af5a53e68d6c8e0826831aaae434510c96a1963ad2f5439a6cdd77d12420cdf470ffb43b0e9446005c1933c12d95fbe10915c141baf438285a6ae00c85f5",
          "sha256": "8e06239cccce57d56aa7b680db5fdaec38dfeedd28e8f9386e9e349ff2374263",
          "sha1": "b31f2f484fe8ef7c85ca309d250818c593a9847c",
          "md5": "8c99a089a4d3b0ccad6e9d5fb5973aca"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_profile-1.0.aar",
          "url": "permission_handler_android_profile-1.0.aar",
          "size": 28749,
          "sha512": "7514af5a53e68d6c8e0826831aaae434510c96a1963ad2f5439a6cdd77d12420cdf470ffb43b0e9446005c1933c12d95fbe10915c141baf438285a6ae00c85f5",
          "sha256": "8e06239cccce57d56aa7b680db5fdaec38dfeedd28e8f9386e9e349ff2374263",
          "sha1": "b31f2f484fe8ef7c85ca309d250818c593a9847c",
          "md5": "8c99a089a4d3b0ccad6e9d5fb5973aca"
        }
      ]
    }
  ]
}
