{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jarvan.tobias",
    "module": "tobias_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "tobias_profile-1.0.aar",
          "url": "tobias_profile-1.0.aar",
          "size": 24658,
          "sha512": "ebbe8e821e3b7975b2f749938f888165cd729d0e1e257076019e356c0f9330260c583cbc5e41c63d66714bc86c026f3617c2bf7ea3aee1e7322f3df80708818d",
          "sha256": "790bf95444560075c78e80daeec595539aab35be1f395df5b7d562f5e65f583c",
          "sha1": "4c3b08eae6c98bdf7ac1212374ad9715478fe13b",
          "md5": "53cdc91c087820486a5be8397ada1a3b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "tobias_profile-1.0.aar",
          "url": "tobias_profile-1.0.aar",
          "size": 24658,
          "sha512": "ebbe8e821e3b7975b2f749938f888165cd729d0e1e257076019e356c0f9330260c583cbc5e41c63d66714bc86c026f3617c2bf7ea3aee1e7322f3df80708818d",
          "sha256": "790bf95444560075c78e80daeec595539aab35be1f395df5b7d562f5e65f583c",
          "sha1": "4c3b08eae6c98bdf7ac1212374ad9715478fe13b",
          "md5": "53cdc91c087820486a5be8397ada1a3b"
        }
      ]
    }
  ]
}
