{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ryanheise.just_audio",
    "module": "just_audio_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-1.0.aar",
          "url": "just_audio_release-1.0.aar",
          "size": 29174,
          "sha512": "2293b983629645a0ddf96ff9a62056308c8f17e54c523f3fff89fcb52fe14055b1ee41b71662907c7464c35834d9969a59d9bf52a968737ab3eaefcfc8a5ce2e",
          "sha256": "0fadcc82b6bebdddb18b6e89d4d648c0c53e42df4140ece5deb35f1af393adf3",
          "sha1": "f3349e9d7e1b1f76f7407929da1d1fe7e71d227e",
          "md5": "941af9f652003521bf915c2c9227b80d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.ryanheise.audio_session",
          "module": "audio_session_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "just_audio_release-1.0.aar",
          "url": "just_audio_release-1.0.aar",
          "size": 29174,
          "sha512": "2293b983629645a0ddf96ff9a62056308c8f17e54c523f3fff89fcb52fe14055b1ee41b71662907c7464c35834d9969a59d9bf52a968737ab3eaefcfc8a5ce2e",
          "sha256": "0fadcc82b6bebdddb18b6e89d4d648c0c53e42df4140ece5deb35f1af393adf3",
          "sha1": "f3349e9d7e1b1f76f7407929da1d1fe7e71d227e",
          "md5": "941af9f652003521bf915c2c9227b80d"
        }
      ]
    }
  ]
}
