{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 158142,
          "sha512": "cb2aa2a0b0614eebd54f08745b2d8e8089fe9a0835ea25bbf394799782a78674b3e63f412372beddb15355e7aa3de0780b76a9ceeff3824cb47a3c70067f8afd",
          "sha256": "1f66ad5bf4a244a706f68d4a6c60f6386f1d42c5372fb31fc313072107727c31",
          "sha1": "c15ef7b99267cc5bdad97dacd844f4acb0d34db7",
          "md5": "b4eb9a4864b52398faa12ea69c9b5bf9"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_debug-1.0.aar",
          "url": "webview_flutter_android_debug-1.0.aar",
          "size": 158142,
          "sha512": "cb2aa2a0b0614eebd54f08745b2d8e8089fe9a0835ea25bbf394799782a78674b3e63f412372beddb15355e7aa3de0780b76a9ceeff3824cb47a3c70067f8afd",
          "sha256": "1f66ad5bf4a244a706f68d4a6c60f6386f1d42c5372fb31fc313072107727c31",
          "sha1": "c15ef7b99267cc5bdad97dacd844f4acb0d34db7",
          "md5": "b4eb9a4864b52398faa12ea69c9b5bf9"
        }
      ]
    }
  ]
}
