{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73615,
          "sha512": "7bc9d581b8f21b5e2f8a147ab5973b05b1ca328c12898c6968db4f1f67fe0a7fe1a02869f13de73d435d5d9a1cd30fbc5769b24063fb0177a79d58d7c4728d4a",
          "sha256": "80d773ede66f376a5c56f01a62291744d8e4618721d398c53e69b857a11ac881",
          "sha1": "c6ffc7f2fdfa7f40c88c1d0c6a2135aa0a8f01d3",
          "md5": "3652a89ca02b54220b81653f5ddec396"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_debug-1.0.aar",
          "url": "image_picker_android_debug-1.0.aar",
          "size": 73615,
          "sha512": "7bc9d581b8f21b5e2f8a147ab5973b05b1ca328c12898c6968db4f1f67fe0a7fe1a02869f13de73d435d5d9a1cd30fbc5769b24063fb0177a79d58d7c4728d4a",
          "sha256": "80d773ede66f376a5c56f01a62291744d8e4618721d398c53e69b857a11ac881",
          "sha1": "c6ffc7f2fdfa7f40c88c1d0c6a2135aa0a8f01d3",
          "md5": "3652a89ca02b54220b81653f5ddec396"
        }
      ]
    }
  ]
}
