{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jarvan.fluwx",
    "module": "fluwx_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "fluwx_profile-1.0.aar",
          "url": "fluwx_profile-1.0.aar",
          "size": 88033,
          "sha512": "6d121e134ae163d2d299d812796d37fd3dd03ff15a69d4463f7d7e29c493d6ae171d678873e224f47e0e3848480ccb606a346721cead58949e75aab3cf77d7aa",
          "sha256": "41e1be531180b447a2b7b5ad5a1757775a3c079c3b4579b16969fab75f32187e",
          "sha1": "eda9998cc3f6eea5380dc479807de9b6242bb909",
          "md5": "b3e3beca1e5ac1295db55bb159601302"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.tencent.mm.opensdk",
          "module": "wechat-sdk-android",
          "version": {
            "requires": "6.8.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "fluwx_profile-1.0.aar",
          "url": "fluwx_profile-1.0.aar",
          "size": 88033,
          "sha512": "6d121e134ae163d2d299d812796d37fd3dd03ff15a69d4463f7d7e29c493d6ae171d678873e224f47e0e3848480ccb606a346721cead58949e75aab3cf77d7aa",
          "sha256": "41e1be531180b447a2b7b5ad5a1757775a3c079c3b4579b16969fab75f32187e",
          "sha1": "eda9998cc3f6eea5380dc479807de9b6242bb909",
          "md5": "b3e3beca1e5ac1295db55bb159601302"
        }
      ]
    }
  ]
}
