{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27959,
          "sha512": "49b6d947522fb4fdecebae9d485b1b6c596407aac74a94c303e1b9386a9929369df8bb360923933f333d4d5b54b5848f2134d326ad4205048a16d2ae56a5ac4d",
          "sha256": "e963db9942a9144db9cad38a3691df9df0686bb46f09aa93084256986be0463c",
          "sha1": "198980e73ef39a8f6f6168d2da6b60a3af67afd1",
          "md5": "4dec32f495bd70fb7c068ebb68d0e7c9"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_debug-1.0.aar",
          "url": "flutter_secure_storage_debug-1.0.aar",
          "size": 27959,
          "sha512": "49b6d947522fb4fdecebae9d485b1b6c596407aac74a94c303e1b9386a9929369df8bb360923933f333d4d5b54b5848f2134d326ad4205048a16d2ae56a5ac4d",
          "sha256": "e963db9942a9144db9cad38a3691df9df0686bb46f09aa93084256986be0463c",
          "sha1": "198980e73ef39a8f6f6168d2da6b60a3af67afd1",
          "md5": "4dec32f495bd70fb7c068ebb68d0e7c9"
        }
      ]
    }
  ]
}
