{
  "formatVersion": "1.1",
  "component": {
    "group": "xyz.canardoux.fluttersound",
    "module": "flutter_sound_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_profile-1.0.aar",
          "url": "flutter_sound_profile-1.0.aar",
          "size": 30081,
          "sha512": "9bb02f6cb54e2d6ebe0a018c480291575f697e1df7e6722a484748190d4dd9df3e6687313e18d64a2a132f205379756a2868ed16d02b989bc716154c849b7d80",
          "sha256": "626ef83360819c87075956d2b49ecbe941017f7213b7976003b4083c0ce86d41",
          "sha1": "b5e3570399d5dcb45428aa744e99518c4ae8044a",
          "md5": "7a96c201e8651ebf689ade1264fffcc8"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.canardoux",
          "module": "flutter_sound_core",
          "version": {
            "requires": "9.11.2"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_sound_profile-1.0.aar",
          "url": "flutter_sound_profile-1.0.aar",
          "size": 30081,
          "sha512": "9bb02f6cb54e2d6ebe0a018c480291575f697e1df7e6722a484748190d4dd9df3e6687313e18d64a2a132f205379756a2868ed16d02b989bc716154c849b7d80",
          "sha256": "626ef83360819c87075956d2b49ecbe941017f7213b7976003b4083c0ce86d41",
          "sha1": "b5e3570399d5dcb45428aa744e99518c4ae8044a",
          "md5": "7a96c201e8651ebf689ade1264fffcc8"
        }
      ]
    }
  ]
}
