{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 13518,
          "sha512": "a29d36036c0c15ae33b02c4c560876791d878ef6746094b9434bab124c1b400635859e3e88c791971b39c63e4d77d0424bf8c21b7e29d1803a95363817c2b358",
          "sha256": "d6f46e2c9491cbf106f6f3de5b52f71984df6b4d2a74277e052ac7c21e761230",
          "sha1": "aabf56f7b59c4d21012d1cfe254c2a32437100f6",
          "md5": "ae4a256871ab605b7f5052ff437e3718"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_debug-1.0.aar",
          "url": "shared_preferences_android_debug-1.0.aar",
          "size": 13518,
          "sha512": "a29d36036c0c15ae33b02c4c560876791d878ef6746094b9434bab124c1b400635859e3e88c791971b39c63e4d77d0424bf8c21b7e29d1803a95363817c2b358",
          "sha256": "d6f46e2c9491cbf106f6f3de5b52f71984df6b4d2a74277e052ac7c21e761230",
          "sha1": "aabf56f7b59c4d21012d1cfe254c2a32437100f6",
          "md5": "ae4a256871ab605b7f5052ff437e3718"
        }
      ]
    }
  ]
}
