{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 148901,
          "sha512": "1ce6c0c8b6dde6d552383a2e0372f23bb42d34d7e2610522ee63695a05364beace64002c2a879847b69c86dcb0feee105ad31f50a0c8448db05741e2d8b64ab0",
          "sha256": "1bd6f0299a8d5366063d431c0d308c018ccdeed9696598dcbc1b41f8e7f09b5b",
          "sha1": "44c20ad9a499be7d687ce841b1178ca148289313",
          "md5": "bfd0de0483bdb1d548aa9c2855c2e881"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_release-1.0.aar",
          "url": "webview_flutter_android_release-1.0.aar",
          "size": 148901,
          "sha512": "1ce6c0c8b6dde6d552383a2e0372f23bb42d34d7e2610522ee63695a05364beace64002c2a879847b69c86dcb0feee105ad31f50a0c8448db05741e2d8b64ab0",
          "sha256": "1bd6f0299a8d5366063d431c0d308c018ccdeed9696598dcbc1b41f8e7f09b5b",
          "sha1": "44c20ad9a499be7d687ce841b1178ca148289313",
          "md5": "bfd0de0483bdb1d548aa9c2855c2e881"
        }
      ]
    }
  ]
}
