{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 9916,
          "sha512": "6f3a0945788df4e9a9b5da245e1f4c1bfc7c5d884ce33aba15479ab1bb51637e37f470bf6366843c3b9cb7988a28ffbf4bab7886fdbe061b410f6ae58361f9bb",
          "sha256": "1419c9a1f338fbe893b1e43e7ae4f4595c89a42816acc4a0ab962faf8889245f",
          "sha1": "a15c01d75695ee283e7a0719fd6a64591ee3c75c",
          "md5": "5fc4cb2abc78e5b167fe5fa81cb376bf"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_profile-1.0.aar",
          "url": "connectivity_plus_profile-1.0.aar",
          "size": 9916,
          "sha512": "6f3a0945788df4e9a9b5da245e1f4c1bfc7c5d884ce33aba15479ab1bb51637e37f470bf6366843c3b9cb7988a28ffbf4bab7886fdbe061b410f6ae58361f9bb",
          "sha256": "1419c9a1f338fbe893b1e43e7ae4f4595c89a42816acc4a0ab962faf8889245f",
          "sha1": "a15c01d75695ee283e7a0719fd6a64591ee3c75c",
          "md5": "5fc4cb2abc78e5b167fe5fa81cb376bf"
        }
      ]
    }
  ]
}
