{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.permissionhandler",
    "module": "permission_handler_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28746,
          "sha512": "76bf96954a18c2ac6c5c2ad03d38e6665ea041bc3e3e508491be180039b3c46d115b5e82d24f42f13b604a1b735c8518dcd72ee254a233cb04a36448f97bbf92",
          "sha256": "3ccb472999ef7c44242db4fdc22e7ed1d306d402ff12d0b546ca5b3d8bdc0132",
          "sha1": "27a18d09f50891aa4a87955d37b070161d643e5b",
          "md5": "e0e05123af0cecda96f5146e170876ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "permission_handler_android_release-1.0.aar",
          "url": "permission_handler_android_release-1.0.aar",
          "size": 28746,
          "sha512": "76bf96954a18c2ac6c5c2ad03d38e6665ea041bc3e3e508491be180039b3c46d115b5e82d24f42f13b604a1b735c8518dcd72ee254a233cb04a36448f97bbf92",
          "sha256": "3ccb472999ef7c44242db4fdc22e7ed1d306d402ff12d0b546ca5b3d8bdc0132",
          "sha1": "27a18d09f50891aa4a87955d37b070161d643e5b",
          "md5": "e0e05123af0cecda96f5146e170876ba"
        }
      ]
    }
  ]
}
