{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.connectivity",
    "module": "connectivity_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 9913,
          "sha512": "ebd2eedc5a696207bb336a688fbd78dea0c677a1355cbb664245e7de7542ad7b48daac95d352a36eef481931fb3c3376eb9f199746de2f5133e4f7e2b84166e4",
          "sha256": "e6bd9a7f24835ed2d5fc24cd56e58440a33be746ca4618af34ee36d80200c31f",
          "sha1": "4cca6582f16f24848f0a692c5c6988ee9e4e2359",
          "md5": "d4af23c43244168a02ac6573d4ec6bfa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "connectivity_plus_release-1.0.aar",
          "url": "connectivity_plus_release-1.0.aar",
          "size": 9913,
          "sha512": "ebd2eedc5a696207bb336a688fbd78dea0c677a1355cbb664245e7de7542ad7b48daac95d352a36eef481931fb3c3376eb9f199746de2f5133e4f7e2b84166e4",
          "sha256": "e6bd9a7f24835ed2d5fc24cd56e58440a33be746ca4618af34ee36d80200c31f",
          "sha1": "4cca6582f16f24848f0a692c5c6988ee9e4e2359",
          "md5": "d4af23c43244168a02ac6573d4ec6bfa"
        }
      ]
    }
  ]
}
