{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jarvan.tobias",
    "module": "tobias_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "tobias_debug-1.0.aar",
          "url": "tobias_debug-1.0.aar",
          "size": 25870,
          "sha512": "df48b4e4e55d35b56897ee5cc3733cfd5f780bd6e5ce1c702ebdc78c83820f29ec36fe20dd6efb3d3e6cc20ae9070d2ecdd2fa2267b9815fec1d1ebf07b4b8a2",
          "sha256": "962dcbf71c3f02b70eefdc77498061f1aa13221322a92a37335a7f8a066cb3ac",
          "sha1": "94cdc231d72365041cf0f1570109c58b96afe221",
          "md5": "c63f0adc6ced7849208de1c52a436a92"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.alipay.sdk",
          "module": "alipaysdk-android",
          "version": {
            "requires": "15.8.17"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "tobias_debug-1.0.aar",
          "url": "tobias_debug-1.0.aar",
          "size": 25870,
          "sha512": "df48b4e4e55d35b56897ee5cc3733cfd5f780bd6e5ce1c702ebdc78c83820f29ec36fe20dd6efb3d3e6cc20ae9070d2ecdd2fa2267b9815fec1d1ebf07b4b8a2",
          "sha256": "962dcbf71c3f02b70eefdc77498061f1aa13221322a92a37335a7f8a066cb3ac",
          "sha1": "94cdc231d72365041cf0f1570109c58b96afe221",
          "md5": "c63f0adc6ced7849208de1c52a436a92"
        }
      ]
    }
  ]
}
