{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.wakelock",
    "module": "wakelock_plus_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_profile-1.0.aar",
          "url": "wakelock_plus_profile-1.0.aar",
          "size": 18546,
          "sha512": "2ac32e90f0d514d1a54919a9f18c2468dbda66573389f5f4e6249bc5a28be381dd947334bed55703d2831727fb685656a668364fa13563b585dd532bb4072d57",
          "sha256": "0053b54ebb6d95ff8510b8c6b7295f7f911f002f8b9020c3ff4e4e2d00880bba",
          "sha1": "99a9c9a201c217acd158bed3dfadda924dcb849c",
          "md5": "51d16f0f7a92abb1f3323a06325996c4"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_profile-1.0.aar",
          "url": "wakelock_plus_profile-1.0.aar",
          "size": 18546,
          "sha512": "2ac32e90f0d514d1a54919a9f18c2468dbda66573389f5f4e6249bc5a28be381dd947334bed55703d2831727fb685656a668364fa13563b585dd532bb4072d57",
          "sha256": "0053b54ebb6d95ff8510b8c6b7295f7f911f002f8b9020c3ff4e4e2d00880bba",
          "sha1": "99a9c9a201c217acd158bed3dfadda924dcb849c",
          "md5": "51d16f0f7a92abb1f3323a06325996c4"
        }
      ]
    }
  ]
}
