{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.webviewflutter",
    "module": "webview_flutter_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 148904,
          "sha512": "7f368721f8ba0f5b1050f4d1ea121fb83042741b9e8e178d7977b59e0ca72155fe04c14104f458cbe257445a4409733bfdff731d28b4fd00d26e30b0fa43220a",
          "sha256": "06d4b79e13fc355bc1b0eda93d7bc1f47a378c4d14505ed8967db5e57d2ee223",
          "sha1": "0f018c312a2428c616ddbe2879c77331378beab6",
          "md5": "4c9b34ae8e91eb333267c114d488a7ab"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.11.0"
          }
        }
      ],
      "files": [
        {
          "name": "webview_flutter_android_profile-1.0.aar",
          "url": "webview_flutter_android_profile-1.0.aar",
          "size": 148904,
          "sha512": "7f368721f8ba0f5b1050f4d1ea121fb83042741b9e8e178d7977b59e0ca72155fe04c14104f458cbe257445a4409733bfdff731d28b4fd00d26e30b0fa43220a",
          "sha256": "06d4b79e13fc355bc1b0eda93d7bc1f47a378c4d14505ed8967db5e57d2ee223",
          "sha1": "0f018c312a2428c616ddbe2879c77331378beab6",
          "md5": "4c9b34ae8e91eb333267c114d488a7ab"
        }
      ]
    }
  ]
}
