{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 69894,
          "sha512": "14d957762a7cbedda088bf4feb673b1e3f0aba75ab57327f191a11dd5b398370f8e5bee97574c506d3432eeaef140787e5b53463b774e0c1d1bcdb4155998e2c",
          "sha256": "90c140351cd27539d291d0aabf36ecd61feed252219e5e426caff73bb03f1772",
          "sha1": "c637535b832d4e84be21f9132c51a6bfa721f98a",
          "md5": "ce1f5625083c7b23cfa9d070ac321710"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 69894,
          "sha512": "14d957762a7cbedda088bf4feb673b1e3f0aba75ab57327f191a11dd5b398370f8e5bee97574c506d3432eeaef140787e5b53463b774e0c1d1bcdb4155998e2c",
          "sha256": "90c140351cd27539d291d0aabf36ecd61feed252219e5e426caff73bb03f1772",
          "sha1": "c637535b832d4e84be21f9132c51a6bfa721f98a",
          "md5": "ce1f5625083c7b23cfa9d070ac321710"
        }
      ]
    }
  ]
}
