{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26713,
          "sha512": "f4223b6bd50858547d5c9eff9173431a4729e9c143ae3f7b5e50fabf4dddefb692d783597c23d1c4381d46b641e2fe095224b7820bb4af81be33beb38fdca7ff",
          "sha256": "d49b2f6f9551b294124e0402cf5504d37abc622da71be1fb90eb7c4c98e65b61",
          "sha1": "8cb8d54ffc81825ce1891c99a640aabe7ce392b9",
          "md5": "c4947eb5b1a09149c7757822ada1a6d9"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_profile-1.0.aar",
          "url": "flutter_secure_storage_profile-1.0.aar",
          "size": 26713,
          "sha512": "f4223b6bd50858547d5c9eff9173431a4729e9c143ae3f7b5e50fabf4dddefb692d783597c23d1c4381d46b641e2fe095224b7820bb4af81be33beb38fdca7ff",
          "sha256": "d49b2f6f9551b294124e0402cf5504d37abc622da71be1fb90eb7c4c98e65b61",
          "sha1": "8cb8d54ffc81825ce1891c99a640aabe7ce392b9",
          "md5": "c4947eb5b1a09149c7757822ada1a6d9"
        }
      ]
    }
  ]
}
