{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39680,
          "sha512": "b2cf25645309971889bbae9d1be79b06024b924795231f27dec8797f2ede2afbc6d6b68ee0b80978bdb0b729e521b7f5f06cdf362508cc07635f7104def58e49",
          "sha256": "1a53545d7eb42c95241d8f61f4a5eedb15e055cc458408c37a52bfdb351681db",
          "sha1": "afb90b4fc8caefd5c1bc2396910618b3312f0bcb",
          "md5": "11d96d6aaa08978b50c0469f55953fc7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-hls",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-dash",
          "version": {
            "requires": "2.18.7"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-smoothstreaming",
          "version": {
            "requires": "2.18.7"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 39680,
          "sha512": "b2cf25645309971889bbae9d1be79b06024b924795231f27dec8797f2ede2afbc6d6b68ee0b80978bdb0b729e521b7f5f06cdf362508cc07635f7104def58e49",
          "sha256": "1a53545d7eb42c95241d8f61f4a5eedb15e055cc458408c37a52bfdb351681db",
          "sha1": "afb90b4fc8caefd5c1bc2396910618b3312f0bcb",
          "md5": "11d96d6aaa08978b50c0469f55953fc7"
        }
      ]
    }
  ]
}
