{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 69892,
          "sha512": "23d30624009aabf94180df1f336ca91e07612d2682d3d56adc6f88ecb76ff0bf4d9b8a5113bf62ac703dc55d5c6c9731f5abfd5d9655a4ff2eacf416d85c3c2d",
          "sha256": "bd50701921106d93bf3663b795eba72c5c27c1e75b8f3a34dd270987cc3aee1c",
          "sha1": "f48700022de83ec16df6c844a60d3e4b62c5d1d9",
          "md5": "1821f7cbe88e5399351e32a98e5488cc"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.7"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_profile-1.0.aar",
          "url": "image_picker_android_profile-1.0.aar",
          "size": 69892,
          "sha512": "23d30624009aabf94180df1f336ca91e07612d2682d3d56adc6f88ecb76ff0bf4d9b8a5113bf62ac703dc55d5c6c9731f5abfd5d9655a4ff2eacf416d85c3c2d",
          "sha256": "bd50701921106d93bf3663b795eba72c5c27c1e75b8f3a34dd270987cc3aee1c",
          "sha1": "f48700022de83ec16df6c844a60d3e4b62c5d1d9",
          "md5": "1821f7cbe88e5399351e32a98e5488cc"
        }
      ]
    }
  ]
}
